/**
 * Dataset Rute Angkot Bogor yang digenerate otomatis dari GTFS (michielbdejong/bogor-angkot-gtfs)
 * Terupdate otomatis via build script.
 */

export const trayekAngkot = [
    {
        "kode": "AK-01",
        "nama": "AK-01",
        "warna": "Hijau",
        "rute": [
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "suryakencana-1",
            "suryakencana-2",
            "roda-siliwangi",
            "siliwangi-1",
            "siliwangi-2",
            "siliwangi-jlsukasari",
            "siliwangi-lawanggintung",
            "lawanggintung-cipaku",
            "Cipaku",
            "diredja-1",
            "diredja-2",
            "diredja-3",
            "diredja-cipinanggading",
            "cipinanggading-1",
            "cipinanggading-2",
            "cipinanggading-ranggamekar",
            "ranggamekar-1",
            "Cipinang Gading",
            "ranggamekar-1",
            "cipinanggading-ranggamekar",
            "cipinanggading-nirwana",
            "nirwana-1",
            "nirwana-2",
            "nirwana-3",
            "nirwana-4",
            "nirwana-5",
            "nirwana-6",
            "nirwana-dreded",
            "dreded-1",
            "dreded-pahlawan",
            "pahlawan-ggaut",
            "pahlawan-layungsari",
            "pahlawan-3",
            "pahlawan-4",
            "pahlawan-empang",
            "halte-empang",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "muslihat-dewisartika",
            "stasiun-paledang",
            "veteran-merdeka",
            "veteran-kemerdekaan",
            "kemerdekaan",
            "merdeka-semeru",
            "merdeka-semeru",
            "Term. Merdeka",
            "salamun-oking",
            "muslihat-oking",
            "stasiun-paledang",
            "muslihat-dewisartika",
            "muslihat-dewisartika",
            "dewisartika-mekah",
            "mekah-gedongsawah",
            "gedongsawah-crossing",
            "kb-gedong-sawah"
        ],
        "jarak_km": 48.3,
        "waktu_menit": 173,
        "tarif": 6000,
        "keterangan": "Trayek AK-01"
    },
    {
        "kode": "AK-02",
        "nama": "AK-02",
        "warna": "Hijau",
        "rute": [
            "Jl. Muslihat",
            "muslihat-dewisartika",
            "stasiun-paledang",
            "muslihat-oking",
            "veteran-merdeka",
            "veteran-kemerdekaan",
            "abdullah-batu",
            "sind-barang-1",
            "sind-barang-2",
            "sind-barang-darulquran",
            "sind-barang-3",
            "sind-barang-4",
            "sind-barang-adjie",
            "adjie-ciampea",
            "Term. Bubulak",
            "adjie-ciampea",
            "sind-barang-adjie",
            "sind-barang-4",
            "sind-barang-3",
            "sind-barang-darulquran",
            "sind-barang-2",
            "sind-barang-1",
            "abdullah-batu",
            "veteran-kemerdekaan",
            "kemerdekaan",
            "merdeka-semeru",
            "veteran-merdeka",
            "muslihat-oking",
            "stasiun-paledang",
            "muslihat-dewisartika",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "suryakencana-1",
            "suryakencana-2",
            "roda-siliwangi",
            "siliwangi-1",
            "siliwangi-2",
            "siliwangi-jlsukasari",
            "siliwangi-lawanggintung",
            "lawanggintung-cipaku",
            "batutulis-pahlawan",
            "pahlawan-1",
            "dreded-pahlawan",
            "pahlawan-ggaut",
            "pahlawan-layungsari",
            "pahlawan-3",
            "pahlawan-4",
            "pahlawan-empang",
            "halte-empang",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat"
        ],
        "jarak_km": 44.8,
        "waktu_menit": 160,
        "tarif": 6000,
        "keterangan": "Trayek AK-02"
    },
    {
        "kode": "AK-03",
        "nama": "AK-03",
        "warna": "Hijau",
        "rute": [
            "Jl. Muslihat",
            "muslihat-dewisartika",
            "stasiun-paledang",
            "muslihat-oking",
            "veteran-merdeka",
            "veteran-kemerdekaan",
            "abdullah-batu",
            "sind-barang-1",
            "sind-barang-2",
            "sind-barang-darulquran",
            "sind-barang-3",
            "sind-barang-4",
            "sind-barang-adjie",
            "adjie-ciampea",
            "Term. Bubulak",
            "adjie-ciampea",
            "sind-barang-adjie",
            "sind-barang-4",
            "sind-barang-3",
            "sind-barang-darulquran",
            "sind-barang-2",
            "sind-barang-1",
            "abdullah-batu",
            "veteran-kemerdekaan",
            "kemerdekaan",
            "merdeka-semeru",
            "veteran-merdeka",
            "muslihat-oking",
            "stasiun-paledang",
            "muslihat-dewisartika",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "salak-1",
            "salak-2",
            "salak-3",
            "Taman Kencana",
            "kencana-2",
            "salak-4",
            "salak-5",
            "Jl. Salak",
            "pangrango-pajajaran",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "Term. Baranangsiang",
            "Jl. Tol",
            "Term. Baranangsiang",
            "bangka-1",
            "pajajaran-ciheuleut",
            "pajajaran-michelle-bakery",
            "pajajaran-ciheuleut",
            "bangka-1",
            "bangka-7",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat"
        ],
        "jarak_km": 45.5,
        "waktu_menit": 163,
        "tarif": 6000,
        "keterangan": "Trayek AK-03"
    },
    {
        "kode": "AK-04",
        "nama": "AK-04",
        "warna": "Hijau",
        "rute": [
            "ggaut-padasuka",
            "padasuka-1",
            "padasuka-cincau",
            "cincau-1",
            "cincau-2",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "halte-empang",
            "pahlawan-empang",
            "pahlawan-4",
            "pahlawan-3",
            "pahlawan-layungsari",
            "pahlawan-ggaut",
            "dreded-pahlawan",
            "pahlawan-1",
            "batutulis-pahlawan",
            "lawanggintung-cipaku",
            "Cipaku",
            "raya-cipaku-1",
            "raya-cipaku-2",
            "raya-cipaku-3",
            "raya-cipaku-4",
            "raya-cipaku-5",
            "raya-cipaku-dekeng",
            "dekeng-1",
            "dekeng-2",
            "Rancamaya",
            "dekeng-4",
            "dekeng-5",
            "dekeng-6",
            "dekeng-7",
            "dekeng-8",
            "dekeng-9",
            "dekeng-10",
            "dekeng-11",
            "Warung Nangka",
            "dekeng-11",
            "dekeng-10",
            "dekeng-9",
            "dekeng-8",
            "dekeng-7",
            "dekeng-6",
            "dekeng-5",
            "dekeng-4",
            "Rancamaya",
            "dekeng-2",
            "dekeng-1",
            "raya-cipaku-dekeng",
            "raya-cipaku-5",
            "raya-cipaku-4",
            "raya-cipaku-3",
            "raya-cipaku-2",
            "raya-cipaku-1",
            "Cipaku",
            "lawanggintung-cipaku",
            "batutulis-pahlawan",
            "pahlawan-1",
            "dreded-pahlawan",
            "pahlawan-ggaut",
            "ggaut-padasuka"
        ],
        "jarak_km": 42.7,
        "waktu_menit": 153,
        "tarif": 6000,
        "keterangan": "Trayek AK-04"
    },
    {
        "kode": "AK-05",
        "nama": "AK-05",
        "warna": "Hijau",
        "rute": [
            "line-05-21",
            "line-05-20",
            "line-05-19",
            "line-05-18",
            "line-05-17",
            "line-05-16",
            "line-05-15",
            "line-05-14",
            "line-05-13",
            "wiradiredja-ikhwan",
            "wiradiredja-swingright",
            "wiradiredja-swingleft",
            "syam-tohir",
            "syam-southturn",
            "syam-tohir",
            "line-05-6",
            "line-05-5",
            "line-05-4",
            "line-05-3",
            "line-05-2",
            "lodaya-M",
            "lodaya-S",
            "pangrango-pajajaran",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "pangrango-pajajaran",
            "lodaya-S",
            "lodaya-M",
            "line-05-2",
            "line-05-3",
            "line-05-4",
            "line-05-5",
            "line-05-6",
            "syam-tohir",
            "syam-norththturn",
            "syam-tohir",
            "wiradiredja-swingleft",
            "wiradiredja-swingright",
            "wiradiredja-ikhwan",
            "line-05-13",
            "line-05-14",
            "line-05-15",
            "line-05-16",
            "line-05-17",
            "line-05-18",
            "line-05-19",
            "line-05-20",
            "line-05-21",
            "Cimahpar",
            "line-05-21"
        ],
        "jarak_km": 45.5,
        "waktu_menit": 163,
        "tarif": 6000,
        "keterangan": "Trayek AK-05"
    },
    {
        "kode": "AK-06",
        "nama": "AK-06",
        "warna": "Hijau",
        "rute": [
            "Ciheuleut",
            "ciheuleut-binamarga",
            "padi-jagung",
            "ciheuleut-binamarga",
            "ciheuleut-pakuanindah",
            "pajajaran-ciheuleut",
            "pajajaran-michelle-bakery",
            "pajajaran-ciheuleut",
            "bangka-1",
            "Term. Baranangsiang",
            "Term. Baranangsiang",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "Term. Baranangsiang",
            "Jl. Tol",
            "Term. Baranangsiang",
            "bangka-1",
            "pajajaran-ciheuleut",
            "ciheuleut-pakuanindah",
            "ciheuleut-binamarga",
            "Ciheuleut",
            "Ciheuleut"
        ],
        "jarak_km": 27.3,
        "waktu_menit": 98,
        "tarif": 6000,
        "keterangan": "Trayek AK-06"
    },
    {
        "kode": "AK-07",
        "nama": "AK-07",
        "warna": "Hijau",
        "rute": [
            "kb-gedong-sawah",
            "Polisi Militer",
            "sudirman-first-corner",
            "ggbaru-sudirman",
            "Jl. Sudirman",
            "Air Mancur",
            "Jl. Pemuda",
            "pemuda-pedes",
            "line-07-4",
            "line-07-5",
            "line-07-6",
            "line-07-7",
            "jambudua-yani",
            "yani-sungai",
            "Jambu Dua",
            "Ciparigi",
            "Jambu Dua",
            "yani-sungai",
            "jambudua-yani",
            "line-07-7",
            "yani-2",
            "Jl. Yani",
            "yani-4",
            "Air Mancur",
            "Jl. Sudirman",
            "ggbaru-sudirman",
            "sudirman-first-corner",
            "pengadilan-gedongsawah",
            "mekah-gedongsawah",
            "gedongsawah-crossing",
            "gedongsawah-dewisartika",
            "muslihat-dewisartika",
            "Jl. Muslihat",
            "kb-gedong-sawah"
        ],
        "jarak_km": 23.8,
        "waktu_menit": 85,
        "tarif": 6000,
        "keterangan": "Trayek AK-07"
    },
    {
        "kode": "AK-07A",
        "nama": "AK-07A",
        "warna": "Hijau",
        "rute": [
            "kb-gedong-sawah",
            "Polisi Militer",
            "sudirman-first-corner",
            "ggbaru-sudirman",
            "Jl. Sudirman",
            "Air Mancur",
            "Jl. Pemuda",
            "pemuda-pedes",
            "line-07-4",
            "line-07-5",
            "line-07-6",
            "line-07-7",
            "jambudua-yani",
            "yani-sungai",
            "Jambu Dua",
            "Ciparigi",
            "Jambu Dua",
            "yani-sungai",
            "jambudua-yani",
            "line-07-7",
            "yani-2",
            "Jl. Yani",
            "yani-4",
            "Air Mancur",
            "Jl. Sudirman",
            "ggbaru-sudirman",
            "sudirman-first-corner",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-gedong-sawah"
        ],
        "jarak_km": 31.5,
        "waktu_menit": 113,
        "tarif": 6000,
        "keterangan": "Trayek AK-07A"
    },
    {
        "kode": "AK-08",
        "nama": "AK-08",
        "warna": "Hijau",
        "rute": [
            "pajajaran-sobana",
            "Jl. Salak",
            "lodaya-N",
            "lodaya-M",
            "lodaya-S",
            "pangrango-pajajaran",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "pangrango-pajajaran",
            "Jl. Salak",
            "pajajaran-sobana",
            "sobana-sungai",
            "sobana-palapuhraya",
            "sobana-sungai",
            "indraprasta-1",
            "Indra Prasta",
            "indraprasta-3",
            "Jambu Dua",
            "pajajaran-sobana"
        ],
        "jarak_km": 23.8,
        "waktu_menit": 85,
        "tarif": 6000,
        "keterangan": "Trayek AK-08"
    },
    {
        "kode": "AK-09",
        "nama": "AK-09",
        "warna": "Hijau",
        "rute": [
            "Ciparigi",
            "Jambu Dua",
            "pajajaran-sobana",
            "Jl. Salak",
            "lodaya-N",
            "lodaya-M",
            "lodaya-S",
            "pangrango-pajajaran",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "Term. Baranangsiang",
            "Jl. Tol",
            "Term. Baranangsiang",
            "bangka-1",
            "pajajaran-ciheuleut",
            "pajajaran-michelle-bakery",
            "pajajaran-pjjindah",
            "pajajaran-durian",
            "pajajaran-ggmesjid",
            "Sukasari",
            "Sukasari",
            "Sukasari",
            "Sukasari",
            "Sukasari",
            "pajajaran-ggmesjid",
            "pajajaran-durian",
            "pajajaran-pjjindah",
            "pajajaran-michelle-bakery",
            "pajajaran-ciheuleut",
            "bangka-1",
            "bangka-7",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "pangrango-pajajaran",
            "Jl. Salak",
            "pajajaran-sobana",
            "Jambu Dua",
            "Ciparigi"
        ],
        "jarak_km": 35.7,
        "waktu_menit": 128,
        "tarif": 6000,
        "keterangan": "Trayek AK-09"
    },
    {
        "kode": "AK-10",
        "nama": "AK-10",
        "warna": "Hijau",
        "rute": [
            "Jl. Muslihat",
            "muslihat-dewisartika",
            "stasiun-paledang",
            "muslihat-dewisartika",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "suryakencana-1",
            "suryakencana-2",
            "roda-siliwangi",
            "siliwangi-1",
            "siliwangi-2",
            "siliwangi-jlsukasari",
            "siliwangi-lawanggintung",
            "Sukasari",
            "Sukasari",
            "pajajaran-ggmesjid",
            "pajajaran-durian",
            "durian-1",
            "durian-2",
            "Bantar Kemang",
            "durian-2",
            "durian-1",
            "pajajaran-durian",
            "pajajaran-ggmesjid",
            "Sukasari",
            "Sukasari",
            "Sukasari",
            "Sukasari",
            "siliwangi-lawanggintung",
            "lawanggintung-cipaku",
            "batutulis-pahlawan",
            "pahlawan-1",
            "dreded-pahlawan",
            "pahlawan-ggaut",
            "pahlawan-layungsari",
            "pahlawan-3",
            "pahlawan-4",
            "pahlawan-empang",
            "halte-empang",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat"
        ],
        "jarak_km": 37.8,
        "waktu_menit": 135,
        "tarif": 6000,
        "keterangan": "Trayek AK-10"
    },
    {
        "kode": "AK-11",
        "nama": "AK-11",
        "warna": "Hijau",
        "rute": [
            "pajajaran-pjjindah",
            "pajajaran-durian",
            "pajajaran-ggmesjid",
            "pajajaran-durian",
            "pajajaran-pjjindah",
            "pajajaran-michelle-bakery",
            "pajajaran-ciheuleut",
            "bangka-1",
            "bangka-7",
            "bangka-otista",
            "otista-roda",
            "roda-1",
            "Pasar Bogor",
            "roda-3",
            "roda-4",
            "roda-siliwangi",
            "siliwangi-1",
            "siliwangi-2",
            "siliwangi-jlsukasari",
            "jlsukasari-1",
            "jlsukasari-2",
            "jlsukasari-pajajaran",
            "pajajaran-ggmesjid",
            "pajajaran-durian",
            "pajajaran-pjjindah",
            "pajajaran-michelle-bakery",
            "pajajaran-pjjindah",
            "pjjindah-1",
            "pjjindah-2",
            "pjjindah-3",
            "pjjindah-4",
            "pjjindah-5",
            "pjjindah-6",
            "pjjindah-7",
            "pjjindah-8",
            "pjjindah-9",
            "pjjindah-bigroad",
            "Pajajaran Indah",
            "pjjindah-bigroad",
            "pjjindah-east-1",
            "pjjindah-east-2",
            "pjjindah-east-1",
            "pjjindah-bigroad",
            "pjjindah-bigroadbend",
            "pjjindah-bigroadturnsouth",
            "pjjindah-bigroadbend",
            "pjjindah-bigroad",
            "pjjindah-9",
            "pjjindah-8",
            "pjjindah-7",
            "pjjindah-6",
            "pjjindah-5",
            "pjjindah-4",
            "pjjindah-3",
            "pjjindah-2",
            "pjjindah-1",
            "pajajaran-pjjindah"
        ],
        "jarak_km": 39.9,
        "waktu_menit": 143,
        "tarif": 6000,
        "keterangan": "Trayek AK-11"
    },
    {
        "kode": "AK-12",
        "nama": "AK-12",
        "warna": "Hijau",
        "rute": [
            "dewisartika-mekah",
            "dewisartika-pengadilan",
            "pengadilan-gedongsawah",
            "sudirman-first-corner",
            "ggbaru-sudirman",
            "Jl. Sudirman",
            "Air Mancur",
            "martadinata-airmancur",
            "martadinata-bubulak",
            "martadinata-2",
            "martadinata-3",
            "martadinata-tentpelajar",
            "tentpelajar",
            "Cimanggu",
            "tentpelajar",
            "martadinata-tentpelajar",
            "mawar-merdeka",
            "Term. Merdeka",
            "salamun-oking",
            "muslihat-oking",
            "muslihat-dewisartika",
            "dewisartika-mekah"
        ],
        "jarak_km": 15.4,
        "waktu_menit": 55,
        "tarif": 6000,
        "keterangan": "Trayek AK-12"
    },
    {
        "kode": "AK-13",
        "nama": "AK-13",
        "warna": "Hijau",
        "rute": [
            "pajajaran-durian",
            "durian-1",
            "durian-2",
            "Bantar Kemang",
            "rambutan",
            "banteng-sungai",
            "katulampa",
            "banteng-sungai",
            "banteng-busyro",
            "Mutiara Bogor Raya",
            "pasirangin-1",
            "pasirangin-novotel",
            "pasirangin-1",
            "Mutiara Bogor Raya",
            "banteng-busyro",
            "banteng-sungai",
            "rambutan",
            "Bantar Kemang",
            "durian-2",
            "durian-1",
            "pajajaran-durian",
            "pajajaran-ggmesjid",
            "pajajaran-durian",
            "pajajaran-pjjindah",
            "pajajaran-michelle-bakery",
            "pajajaran-ciheuleut",
            "bangka-1",
            "bangka-7",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "Jl. Pangrango",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "Term. Baranangsiang",
            "Jl. Tol",
            "Term. Baranangsiang",
            "bangka-1",
            "pajajaran-ciheuleut",
            "pajajaran-michelle-bakery",
            "pajajaran-pjjindah",
            "pajajaran-durian"
        ],
        "jarak_km": 37.1,
        "waktu_menit": 133,
        "tarif": 6000,
        "keterangan": "Trayek AK-13"
    },
    {
        "kode": "AK-14",
        "nama": "AK-14",
        "warna": "Hijau",
        "rute": [
            "batutulis-pahlawan",
            "pahlawan-1",
            "dreded-pahlawan",
            "pahlawan-ggaut",
            "pahlawan-layungsari",
            "layungsari-sedane",
            "sedane-pahlawan-empang",
            "empang-1",
            "empang-2",
            "empang-3",
            "empang-suryalaga-kapten",
            "suryalaga-1",
            "suryalaga-2",
            "suryalaga-3",
            "suryalaga-4",
            "suryalaga-5",
            "suryalaga-ciomas",
            "abdullah-batu",
            "sind-barang-1",
            "sind-barang-2",
            "sind-barang-darulquran",
            "sind-barang-3",
            "sind-barang-4",
            "sind-barang-adjie",
            "adjie-ciampea",
            "Term. Bubulak",
            "adjie-ciampea",
            "sind-barang-adjie",
            "sind-barang-4",
            "sind-barang-3",
            "sind-barang-darulquran",
            "sind-barang-2",
            "sind-barang-1",
            "abdullah-batu",
            "suryalaga-ciomas",
            "suryalaga-5",
            "suryalaga-4",
            "suryalaga-3",
            "suryalaga-2",
            "suryalaga-1",
            "empang-suryalaga-kapten",
            "empang-3",
            "empang-2",
            "empang-1",
            "sedane-pahlawan-empang",
            "pahlawan-empang",
            "pahlawan-4",
            "pahlawan-3",
            "pahlawan-layungsari",
            "pahlawan-ggaut",
            "dreded-pahlawan",
            "pahlawan-1",
            "batutulis-pahlawan",
            "siliwangi-2",
            "siliwangi-jlsukasari",
            "siliwangi-lawanggintung",
            "lawanggintung-cipaku",
            "batutulis-pahlawan"
        ],
        "jarak_km": 40.6,
        "waktu_menit": 145,
        "tarif": 6000,
        "keterangan": "Trayek AK-14"
    },
    {
        "kode": "AK-15",
        "nama": "AK-15",
        "warna": "Hijau",
        "rute": [
            "cifor-ciampea",
            "bubulak-far-exit",
            "cifor-1",
            "Jl. Cifor",
            "cifor-3",
            "cifor-4",
            "cifor-5",
            "cifor-6",
            "cifor-7",
            "cifor-8",
            "cifor-9",
            "cifor-rejoin",
            "pinus-1",
            "pinus-2",
            "pinus-3",
            "pinus-4",
            "pinus-cangkrang",
            "Sindang Barang Jero",
            "cangkrang-2",
            "cangkrang-3",
            "cangkrang-4",
            "cangkrang-5",
            "cifor-rejoin",
            "cifor-9",
            "cifor-8",
            "cifor-7",
            "cifor-6",
            "cifor-5",
            "cifor-4",
            "cifor-3",
            "Jl. Cifor",
            "cifor-1",
            "bubulak-far-exit",
            "cifor-ciampea",
            "Term. Bubulak",
            "adjie-ciampea",
            "sind-barang-adjie",
            "sind-barang-4",
            "sind-barang-3",
            "sind-barang-darulquran",
            "Bogor Golf Club",
            "semboja-semeru",
            "mawar-merdeka",
            "Term. Merdeka",
            "merdeka-semeru",
            "kemerdekaan",
            "semboja-semeru",
            "Bogor Golf Club",
            "sind-barang-darulquran",
            "sind-barang-3",
            "sind-barang-4",
            "sind-barang-adjie",
            "adjie-ciampea",
            "Term. Bubulak",
            "cifor-ciampea"
        ],
        "jarak_km": 38.5,
        "waktu_menit": 138,
        "tarif": 6000,
        "keterangan": "Trayek AK-15"
    },
    {
        "kode": "AK-16",
        "nama": "AK-16",
        "warna": "Hijau",
        "rute": [
            "Jl. Sudirman",
            "sawojajar-cibalok",
            "Pasar Anyar",
            "ggbaru-sudirman",
            "Jl. Sudirman",
            "Air Mancur",
            "Jl. Pemuda",
            "pemuda-pedes",
            "pedes-bendrightatstart",
            "pedes-sungai",
            "pedes-iskandar",
            "iskandar-majujaya",
            "iskandar-20-rejions",
            "iskandar-ciampea-Y",
            "iskandar-bendright",
            "iskandar-kencana",
            "iskandar-19-turns-N",
            "Salabenda",
            "iskandar-19-turns-N",
            "iskandar-kencana",
            "iskandar-bendright",
            "iskandar-ciampea-Y",
            "iskandar-20-rejions",
            "iskandar-majujaya",
            "pedes-iskandar",
            "Jl. Iskandar (Jalan Baru)",
            "pedes-iskandar",
            "pedes-sungai",
            "pedes-bendrightatstart",
            "pemuda-pedes",
            "Jl. Pemuda",
            "Air Mancur",
            "Jl. Sudirman"
        ],
        "jarak_km": 23.1,
        "waktu_menit": 83,
        "tarif": 6000,
        "keterangan": "Trayek AK-16"
    },
    {
        "kode": "AK-17",
        "nama": "AK-17",
        "warna": "Hijau",
        "rute": [
            "Bina Marga",
            "ciheuleut-binamarga",
            "padi-jagung",
            "padi-ramp",
            "ramp-syam",
            "syam-start",
            "syam-papapia",
            "syam-southturn",
            "syam-tohir",
            "syam-norththturn",
            "syam-tohir",
            "wiradiredja-swingleft",
            "wiradiredja-swingright",
            "wiradiredja-ikhwan",
            "wiradiredja-sogiri",
            "sogiri-swingleft",
            "sogiri-swingright",
            "Tanah Baru",
            "tanahbaru-swingright",
            "tanahbaru-tol",
            "tanahbaru-bendright",
            "tanahbaru-bendleft1",
            "tanahbaru-bendleft2",
            "tanahbaru-bendleft3",
            "tanahbaru-almostthere",
            "Pomad",
            "tanahbaru-almostthere",
            "tanahbaru-bendleft3",
            "tanahbaru-bendleft2",
            "tanahbaru-bendleft1",
            "tanahbaru-bendright",
            "tanahbaru-tol",
            "tanahbaru-swingright",
            "Tanah Baru",
            "sogiri-swingright",
            "sogiri-swingleft",
            "wiradiredja-sogiri",
            "wiradiredja-ikhwan",
            "wiradiredja-swingright",
            "wiradiredja-swingleft",
            "syam-tohir",
            "syam-southturn",
            "syam-papapia",
            "syam-start",
            "syam-turn",
            "ramp-syam",
            "padi-ramp",
            "padi-jagung",
            "ciheuleut-binamarga",
            "Bina Marga"
        ],
        "jarak_km": 35,
        "waktu_menit": 125,
        "tarif": 6000,
        "keterangan": "Trayek AK-17"
    },
    {
        "kode": "AK-18",
        "nama": "AK-18",
        "warna": "Hijau",
        "rute": [
            "Ramayana (BTM)",
            "halte-empang",
            "pahlawan-empang",
            "sedane-pahlawan-empang",
            "empang-1",
            "empang-2",
            "empang-3",
            "empang-suryalaga-kapten",
            "kapten-Y",
            "to-cibeureum-1",
            "to-cibeureum-2",
            "to-cibeureum-3",
            "jl-cibeureum-1",
            "jl-cibeureum-2",
            "jl-cibeureum-3",
            "jl-cibeureum--over-river",
            "jl-cibeureum-4",
            "jl-cibeureum-5",
            "jl-cibeureum-mekar-sari",
            "jl-cibeureum-meander",
            "jl-cibeureum-smallsideroad",
            "jl-cibeureum-backatriver",
            "jl-cibeureum-backatriveragain",
            "jl-cibeureum-riverbendsright",
            "jl-cibeureum-riverbendsleft",
            "jl-cibeureum-lastbend",
            "jl-cibeureum-harmony",
            "Mulyaharja",
            "jl-cibeureum-harmony",
            "jl-cibeureum-lastbend",
            "jl-cibeureum-riverbendsleft",
            "jl-cibeureum-riverbendsright",
            "jl-cibeureum-backatriveragain",
            "jl-cibeureum-backatriver",
            "jl-cibeureum-smallsideroad",
            "jl-cibeureum-meander",
            "jl-cibeureum-mekar-sari",
            "jl-cibeureum-5",
            "jl-cibeureum-4",
            "jl-cibeureum--over-river",
            "jl-cibeureum-3",
            "jl-cibeureum-2",
            "jl-cibeureum-1",
            "to-cibeureum-3",
            "to-cibeureum-2",
            "to-cibeureum-1",
            "kapten-Y",
            "empang-suryalaga-kapten",
            "empang-3",
            "empang-2",
            "empang-1",
            "sedane-pahlawan-empang",
            "pahlawan-empang",
            "pahlawan-4",
            "pahlawan-3",
            "pahlawan-layungsari",
            "pahlawan-ggaut",
            "ggaut-padasuka",
            "padasuka-1",
            "padasuka-cincau",
            "cincau-1",
            "cincau-2",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)"
        ],
        "jarak_km": 45.5,
        "waktu_menit": 163,
        "tarif": 6000,
        "keterangan": "Trayek AK-18"
    },
    {
        "kode": "AK-19",
        "nama": "AK-19",
        "warna": "Hijau",
        "rute": [
            "bubulak-far-exit",
            "cifor-ciampea",
            "ciampea-before-river",
            "ciampea-towards-iskandar",
            "iskandar-ciampea-Y",
            "iskandar-bendright",
            "iskandar-kencana",
            "iskandar-19-turns-N",
            "iskandar-kencana",
            "kencana-1-bend-right",
            "kencana-2-bend-left",
            "kencana-3-over-river",
            "kencana-4-setapak",
            "kencana-5-left",
            "kencana-6-right",
            "kencana-corner-kalimurni",
            "kalimurni-1-right",
            "kalimurni-2-left",
            "kalimurni-pendidikan",
            "Taman Griya Kencana",
            "kalimurni-pendidikan",
            "kalimurni-2-left",
            "kalimurni-1-right",
            "kencana-corner-kalimurni",
            "kencana-6-right",
            "kencana-5-left",
            "kencana-4-setapak",
            "kencana-3-over-river",
            "kencana-2-bend-left",
            "kencana-1-bend-right",
            "iskandar-kencana",
            "iskandar-bendright",
            "iskandar-ciampea-Y",
            "ciampea-towards-iskandar",
            "ciampea-before-river",
            "cifor-ciampea",
            "Term. Bubulak",
            "bubulak-far-exit"
        ],
        "jarak_km": 26.6,
        "waktu_menit": 95,
        "tarif": 6000,
        "keterangan": "Trayek AK-19"
    },
    {
        "kode": "AK-20",
        "nama": "AK-20",
        "warna": "Hijau",
        "rute": [
            "Jl. Sudirman",
            "sawojajar-cibalok",
            "Pasar Anyar",
            "ggbaru-sudirman",
            "Jl. Sudirman",
            "Air Mancur",
            "Jl. Pemuda",
            "pemuda-pedes",
            "pedes-bendrightatstart",
            "pedes-sungai",
            "pedes-iskandar",
            "iskandar-majujaya",
            "iskandar-20-rejions",
            "cimanggu-wates-1",
            "cimanggu-wates-setapak",
            "setapak-1",
            "setapak-2",
            "setapak-3",
            "setapak-bukitcimanggu",
            "setapak-4",
            "setapak-5",
            "setapak-6",
            "setapak-7",
            "kencana-4-setapak",
            "kencana-5-left",
            "kencana-6-right",
            "kencana-corner-kalimurni",
            "kalimurni-1-right",
            "kalimurni-2-left",
            "kalimurni-pendidikan",
            "Taman Griya Kencana",
            "kalimurni-pendidikan",
            "kalimurni-2-left",
            "kalimurni-1-right",
            "kencana-corner-kalimurni",
            "kencana-6-right",
            "kencana-5-left",
            "kencana-4-setapak",
            "setapak-7",
            "setapak-6",
            "setapak-5",
            "setapak-4",
            "setapak-bukitcimanggu",
            "setapak-3",
            "setapak-2",
            "setapak-1",
            "cimanggu-wates-setapak",
            "cimanggu-wates-1",
            "iskandar-20-rejions",
            "iskandar-majujaya",
            "pedes-iskandar",
            "Jl. Iskandar (Jalan Baru)",
            "pedes-iskandar",
            "pedes-sungai",
            "pedes-bendrightatstart",
            "pemuda-pedes",
            "Jl. Pemuda",
            "Air Mancur",
            "Jl. Sudirman"
        ],
        "jarak_km": 41.3,
        "waktu_menit": 148,
        "tarif": 6000,
        "keterangan": "Trayek AK-20"
    },
    {
        "kode": "AK-21",
        "nama": "AK-21",
        "warna": "Hijau",
        "rute": [
            "Botani Square",
            "Botani Square",
            "Term. Baranangsiang",
            "Jl. Tol",
            "Term. Baranangsiang",
            "bangka-1",
            "pajajaran-ciheuleut",
            "pajajaran-michelle-bakery",
            "pajajaran-pjjindah",
            "pajajaran-durian",
            "pajajaran-ggmesjid",
            "Sukasari",
            "Sukasari",
            "Sukasari",
            "line-21-11",
            "line-21-12",
            "line-21-13",
            "line-21-14",
            "line-21-15",
            "line-21-16",
            "line-21-17",
            "line-21-18",
            "line-21-19",
            "Ciawi",
            "line-21-19",
            "line-21-18",
            "line-21-17",
            "line-21-16",
            "line-21-15",
            "line-21-14",
            "line-21-13",
            "line-21-12",
            "line-21-11",
            "Sukasari",
            "Sukasari",
            "Sukasari",
            "pajajaran-ggmesjid",
            "pajajaran-durian",
            "pajajaran-pjjindah",
            "pajajaran-michelle-bakery",
            "pajajaran-ciheuleut",
            "bangka-1",
            "Term. Baranangsiang",
            "Term. Baranangsiang",
            "Botani Square",
            "Botani Square",
            "Botani Square"
        ],
        "jarak_km": 32.9,
        "waktu_menit": 118,
        "tarif": 6000,
        "keterangan": "Trayek AK-21"
    },
    {
        "kode": "AK-22",
        "nama": "AK-22",
        "warna": "Hijau",
        "rute": [
            "kb-gedong-sawah",
            "Polisi Militer",
            "sudirman-first-corner",
            "ggbaru-sudirman",
            "Jl. Sudirman",
            "Air Mancur",
            "martadinata-airmancur",
            "martadinata-bubulak",
            "jl-bubulak-1",
            "jl-bubulak-pondok-rumput",
            "Pondok Rumput",
            "jl-bubulak-pondok-rumput",
            "jl-bubulak-1",
            "martadinata-bubulak",
            "martadinata-airmancur",
            "Air Mancur",
            "Jl. Sudirman",
            "ggbaru-sudirman",
            "sudirman-first-corner",
            "pengadilan-gedongsawah",
            "mekah-gedongsawah",
            "gedongsawah-crossing",
            "gedongsawah-dewisartika",
            "muslihat-dewisartika",
            "Jl. Muslihat",
            "kb-gedong-sawah"
        ],
        "jarak_km": 18.2,
        "waktu_menit": 65,
        "tarif": 6000,
        "keterangan": "Trayek AK-22"
    },
    {
        "kode": "AK-23",
        "nama": "AK-23",
        "warna": "Hijau",
        "rute": [
            "ciparigi-3",
            "adnawijaya-1",
            "adnawijaya-2",
            "adnawijaya-3",
            "adnawijaya-4",
            "adnawijaya-5",
            "sobana-palapuhraya",
            "sobana-sungai",
            "pajajaran-sobana",
            "Jl. Salak",
            "lodaya-N",
            "lodaya-M",
            "lodaya-S",
            "pangrango-pajajaran",
            "Kebun Raya",
            "Botani Square",
            "Botani Square",
            "bangka-otista",
            "otista-roda",
            "otista-roda",
            "China Town",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Ramayana (BTM)",
            "Jl. Muslihat",
            "kb-gedong-sawah",
            "Polisi Militer",
            "kb-salak",
            "kb-salak",
            "kb-salak",
            "salak-1",
            "salak-2",
            "salak-3",
            "Taman Kencana",
            "ciremai-1",
            "ciremai-2",
            "ciremai-3",
            "ciremai-4",
            "ciremai-5",
            "ciremai-6",
            "ciremai-7",
            "ciremai-8",
            "ciremai-9",
            "ciremai-jambudua",
            "jambudua-1",
            "jambudua-2",
            "jambudua-3",
            "jambudua-yani",
            "yani-sungai",
            "Jambu Dua",
            "ciparigi-3"
        ],
        "jarak_km": 35.7,
        "waktu_menit": 128,
        "tarif": 6000,
        "keterangan": "Trayek AK-23"
    }
];

export const aliasLokasi = {
    "empang": "Empang",
    "pasar bogor": "Pasar Bogor",
    "pasar anyar": "Pasar Anyar",
    "btm": "BTM",
    "botani square": "BTM",
    "taman kencana": "Taman Kencana",
    "ciawi": "Terminal Ciawi",
    "terminal ciawi": "Terminal Ciawi",
    "baranangsiang": "Terminal Baranangsiang",
    "terminal baranangsiang": "Terminal Baranangsiang",
    "bubulak": "Terminal Bubulak",
    "terminal bubulak": "Terminal Bubulak",
    "laladon": "Laladon",
    "ciapus": "Ciapus",
    "ciomas": "Ciomas",
    "sukasari": "Sukasari",
    "kb-gedong-sawah": "kb-gedong-sawah",
    "polisi militer": "Polisi Militer",
    "kb-salak": "kb-salak",
    "jl. pangrango": "Jl. Pangrango",
    "kebun raya": "Kebun Raya",
    "bangka-otista": "bangka-otista",
    "otista-roda": "otista-roda",
    "china town": "China Town",
    "suryakencana-1": "suryakencana-1",
    "suryakencana-2": "suryakencana-2",
    "roda-siliwangi": "roda-siliwangi",
    "siliwangi-1": "siliwangi-1",
    "siliwangi-2": "siliwangi-2",
    "siliwangi-jlsukasari": "siliwangi-jlsukasari",
    "siliwangi-lawanggintung": "siliwangi-lawanggintung",
    "lawanggintung-cipaku": "lawanggintung-cipaku",
    "cipaku": "Cipaku",
    "diredja-1": "diredja-1",
    "diredja-2": "diredja-2",
    "diredja-3": "diredja-3",
    "diredja-cipinanggading": "diredja-cipinanggading",
    "cipinanggading-1": "cipinanggading-1",
    "cipinanggading-2": "cipinanggading-2",
    "cipinanggading-ranggamekar": "cipinanggading-ranggamekar",
    "ranggamekar-1": "ranggamekar-1",
    "cipinang gading": "Cipinang Gading",
    "cipinanggading-nirwana": "cipinanggading-nirwana",
    "nirwana-1": "nirwana-1",
    "nirwana-2": "nirwana-2",
    "nirwana-3": "nirwana-3",
    "nirwana-4": "nirwana-4",
    "nirwana-5": "nirwana-5",
    "nirwana-6": "nirwana-6",
    "nirwana-dreded": "nirwana-dreded",
    "dreded-1": "dreded-1",
    "dreded-pahlawan": "dreded-pahlawan",
    "pahlawan-ggaut": "pahlawan-ggaut",
    "pahlawan-layungsari": "pahlawan-layungsari",
    "pahlawan-3": "pahlawan-3",
    "pahlawan-4": "pahlawan-4",
    "pahlawan-empang": "pahlawan-empang",
    "halte-empang": "halte-empang",
    "ramayana (btm)": "Ramayana (BTM)",
    "jl. muslihat": "Jl. Muslihat",
    "muslihat-dewisartika": "muslihat-dewisartika",
    "stasiun-paledang": "stasiun-paledang",
    "veteran-merdeka": "veteran-merdeka",
    "veteran-kemerdekaan": "veteran-kemerdekaan",
    "kemerdekaan": "kemerdekaan",
    "merdeka-semeru": "merdeka-semeru",
    "term. merdeka": "Term. Merdeka",
    "salamun-oking": "salamun-oking",
    "muslihat-oking": "muslihat-oking",
    "dewisartika-mekah": "dewisartika-mekah",
    "mekah-gedongsawah": "mekah-gedongsawah",
    "gedongsawah-crossing": "gedongsawah-crossing",
    "abdullah-batu": "abdullah-batu",
    "sind-barang-1": "sind-barang-1",
    "sind-barang-2": "sind-barang-2",
    "sind-barang-darulquran": "sind-barang-darulquran",
    "sind-barang-3": "sind-barang-3",
    "sind-barang-4": "sind-barang-4",
    "sind-barang-adjie": "sind-barang-adjie",
    "adjie-ciampea": "adjie-ciampea",
    "term. bubulak": "Term. Bubulak",
    "batutulis-pahlawan": "batutulis-pahlawan",
    "pahlawan-1": "pahlawan-1",
    "salak-1": "salak-1",
    "salak-2": "salak-2",
    "salak-3": "salak-3",
    "kencana-2": "kencana-2",
    "salak-4": "salak-4",
    "salak-5": "salak-5",
    "jl. salak": "Jl. Salak",
    "pangrango-pajajaran": "pangrango-pajajaran",
    "term. baranangsiang": "Term. Baranangsiang",
    "jl. tol": "Jl. Tol",
    "bangka-1": "bangka-1",
    "pajajaran-ciheuleut": "pajajaran-ciheuleut",
    "pajajaran-michelle-bakery": "pajajaran-michelle-bakery",
    "bangka-7": "bangka-7",
    "ggaut-padasuka": "ggaut-padasuka",
    "padasuka-1": "padasuka-1",
    "padasuka-cincau": "padasuka-cincau",
    "cincau-1": "cincau-1",
    "cincau-2": "cincau-2",
    "raya-cipaku-1": "raya-cipaku-1",
    "raya-cipaku-2": "raya-cipaku-2",
    "raya-cipaku-3": "raya-cipaku-3",
    "raya-cipaku-4": "raya-cipaku-4",
    "raya-cipaku-5": "raya-cipaku-5",
    "raya-cipaku-dekeng": "raya-cipaku-dekeng",
    "dekeng-1": "dekeng-1",
    "dekeng-2": "dekeng-2",
    "rancamaya": "Rancamaya",
    "dekeng-4": "dekeng-4",
    "dekeng-5": "dekeng-5",
    "dekeng-6": "dekeng-6",
    "dekeng-7": "dekeng-7",
    "dekeng-8": "dekeng-8",
    "dekeng-9": "dekeng-9",
    "dekeng-10": "dekeng-10",
    "dekeng-11": "dekeng-11",
    "warung nangka": "Warung Nangka",
    "line-05-21": "line-05-21",
    "line-05-20": "line-05-20",
    "line-05-19": "line-05-19",
    "line-05-18": "line-05-18",
    "line-05-17": "line-05-17",
    "line-05-16": "line-05-16",
    "line-05-15": "line-05-15",
    "line-05-14": "line-05-14",
    "line-05-13": "line-05-13",
    "wiradiredja-ikhwan": "wiradiredja-ikhwan",
    "wiradiredja-swingright": "wiradiredja-swingright",
    "wiradiredja-swingleft": "wiradiredja-swingleft",
    "syam-tohir": "syam-tohir",
    "syam-southturn": "syam-southturn",
    "line-05-6": "line-05-6",
    "line-05-5": "line-05-5",
    "line-05-4": "line-05-4",
    "line-05-3": "line-05-3",
    "line-05-2": "line-05-2",
    "lodaya-m": "lodaya-M",
    "lodaya-s": "lodaya-S",
    "syam-norththturn": "syam-norththturn",
    "cimahpar": "Cimahpar",
    "ciheuleut": "Ciheuleut",
    "ciheuleut-binamarga": "ciheuleut-binamarga",
    "padi-jagung": "padi-jagung",
    "ciheuleut-pakuanindah": "ciheuleut-pakuanindah",
    "sudirman-first-corner": "sudirman-first-corner",
    "ggbaru-sudirman": "ggbaru-sudirman",
    "jl. sudirman": "Jl. Sudirman",
    "air mancur": "Air Mancur",
    "jl. pemuda": "Jl. Pemuda",
    "pemuda-pedes": "pemuda-pedes",
    "line-07-4": "line-07-4",
    "line-07-5": "line-07-5",
    "line-07-6": "line-07-6",
    "line-07-7": "line-07-7",
    "jambudua-yani": "jambudua-yani",
    "yani-sungai": "yani-sungai",
    "jambu dua": "Jambu Dua",
    "ciparigi": "Ciparigi",
    "yani-2": "yani-2",
    "jl. yani": "Jl. Yani",
    "yani-4": "yani-4",
    "pengadilan-gedongsawah": "pengadilan-gedongsawah",
    "gedongsawah-dewisartika": "gedongsawah-dewisartika",
    "pajajaran-sobana": "pajajaran-sobana",
    "lodaya-n": "lodaya-N",
    "sobana-sungai": "sobana-sungai",
    "sobana-palapuhraya": "sobana-palapuhraya",
    "indraprasta-1": "indraprasta-1",
    "indra prasta": "Indra Prasta",
    "indraprasta-3": "indraprasta-3",
    "pajajaran-pjjindah": "pajajaran-pjjindah",
    "pajajaran-durian": "pajajaran-durian",
    "pajajaran-ggmesjid": "pajajaran-ggmesjid",
    "durian-1": "durian-1",
    "durian-2": "durian-2",
    "bantar kemang": "Bantar Kemang",
    "roda-1": "roda-1",
    "roda-3": "roda-3",
    "roda-4": "roda-4",
    "jlsukasari-1": "jlsukasari-1",
    "jlsukasari-2": "jlsukasari-2",
    "jlsukasari-pajajaran": "jlsukasari-pajajaran",
    "pjjindah-1": "pjjindah-1",
    "pjjindah-2": "pjjindah-2",
    "pjjindah-3": "pjjindah-3",
    "pjjindah-4": "pjjindah-4",
    "pjjindah-5": "pjjindah-5",
    "pjjindah-6": "pjjindah-6",
    "pjjindah-7": "pjjindah-7",
    "pjjindah-8": "pjjindah-8",
    "pjjindah-9": "pjjindah-9",
    "pjjindah-bigroad": "pjjindah-bigroad",
    "pajajaran indah": "Pajajaran Indah",
    "pjjindah-east-1": "pjjindah-east-1",
    "pjjindah-east-2": "pjjindah-east-2",
    "pjjindah-bigroadbend": "pjjindah-bigroadbend",
    "pjjindah-bigroadturnsouth": "pjjindah-bigroadturnsouth",
    "dewisartika-pengadilan": "dewisartika-pengadilan",
    "martadinata-airmancur": "martadinata-airmancur",
    "martadinata-bubulak": "martadinata-bubulak",
    "martadinata-2": "martadinata-2",
    "martadinata-3": "martadinata-3",
    "martadinata-tentpelajar": "martadinata-tentpelajar",
    "tentpelajar": "tentpelajar",
    "cimanggu": "Cimanggu",
    "mawar-merdeka": "mawar-merdeka",
    "rambutan": "rambutan",
    "banteng-sungai": "banteng-sungai",
    "katulampa": "katulampa",
    "banteng-busyro": "banteng-busyro",
    "mutiara bogor raya": "Mutiara Bogor Raya",
    "pasirangin-1": "pasirangin-1",
    "pasirangin-novotel": "pasirangin-novotel",
    "layungsari-sedane": "layungsari-sedane",
    "sedane-pahlawan-empang": "sedane-pahlawan-empang",
    "empang-1": "empang-1",
    "empang-2": "empang-2",
    "empang-3": "empang-3",
    "empang-suryalaga-kapten": "empang-suryalaga-kapten",
    "suryalaga-1": "suryalaga-1",
    "suryalaga-2": "suryalaga-2",
    "suryalaga-3": "suryalaga-3",
    "suryalaga-4": "suryalaga-4",
    "suryalaga-5": "suryalaga-5",
    "suryalaga-ciomas": "suryalaga-ciomas",
    "cifor-ciampea": "cifor-ciampea",
    "bubulak-far-exit": "bubulak-far-exit",
    "cifor-1": "cifor-1",
    "jl. cifor": "Jl. Cifor",
    "cifor-3": "cifor-3",
    "cifor-4": "cifor-4",
    "cifor-5": "cifor-5",
    "cifor-6": "cifor-6",
    "cifor-7": "cifor-7",
    "cifor-8": "cifor-8",
    "cifor-9": "cifor-9",
    "cifor-rejoin": "cifor-rejoin",
    "pinus-1": "pinus-1",
    "pinus-2": "pinus-2",
    "pinus-3": "pinus-3",
    "pinus-4": "pinus-4",
    "pinus-cangkrang": "pinus-cangkrang",
    "sindang barang jero": "Sindang Barang Jero",
    "cangkrang-2": "cangkrang-2",
    "cangkrang-3": "cangkrang-3",
    "cangkrang-4": "cangkrang-4",
    "cangkrang-5": "cangkrang-5",
    "bogor golf club": "Bogor Golf Club",
    "semboja-semeru": "semboja-semeru",
    "sawojajar-cibalok": "sawojajar-cibalok",
    "pedes-bendrightatstart": "pedes-bendrightatstart",
    "pedes-sungai": "pedes-sungai",
    "pedes-iskandar": "pedes-iskandar",
    "iskandar-majujaya": "iskandar-majujaya",
    "iskandar-20-rejions": "iskandar-20-rejions",
    "iskandar-ciampea-y": "iskandar-ciampea-Y",
    "iskandar-bendright": "iskandar-bendright",
    "iskandar-kencana": "iskandar-kencana",
    "iskandar-19-turns-n": "iskandar-19-turns-N",
    "salabenda": "Salabenda",
    "jl. iskandar (jalan baru)": "Jl. Iskandar (Jalan Baru)",
    "bina marga": "Bina Marga",
    "padi-ramp": "padi-ramp",
    "ramp-syam": "ramp-syam",
    "syam-start": "syam-start",
    "syam-papapia": "syam-papapia",
    "wiradiredja-sogiri": "wiradiredja-sogiri",
    "sogiri-swingleft": "sogiri-swingleft",
    "sogiri-swingright": "sogiri-swingright",
    "tanah baru": "Tanah Baru",
    "tanahbaru-swingright": "tanahbaru-swingright",
    "tanahbaru-tol": "tanahbaru-tol",
    "tanahbaru-bendright": "tanahbaru-bendright",
    "tanahbaru-bendleft1": "tanahbaru-bendleft1",
    "tanahbaru-bendleft2": "tanahbaru-bendleft2",
    "tanahbaru-bendleft3": "tanahbaru-bendleft3",
    "tanahbaru-almostthere": "tanahbaru-almostthere",
    "pomad": "Pomad",
    "syam-turn": "syam-turn",
    "kapten-y": "kapten-Y",
    "to-cibeureum-1": "to-cibeureum-1",
    "to-cibeureum-2": "to-cibeureum-2",
    "to-cibeureum-3": "to-cibeureum-3",
    "jl-cibeureum-1": "jl-cibeureum-1",
    "jl-cibeureum-2": "jl-cibeureum-2",
    "jl-cibeureum-3": "jl-cibeureum-3",
    "jl-cibeureum--over-river": "jl-cibeureum--over-river",
    "jl-cibeureum-4": "jl-cibeureum-4",
    "jl-cibeureum-5": "jl-cibeureum-5",
    "jl-cibeureum-mekar-sari": "jl-cibeureum-mekar-sari",
    "jl-cibeureum-meander": "jl-cibeureum-meander",
    "jl-cibeureum-smallsideroad": "jl-cibeureum-smallsideroad",
    "jl-cibeureum-backatriver": "jl-cibeureum-backatriver",
    "jl-cibeureum-backatriveragain": "jl-cibeureum-backatriveragain",
    "jl-cibeureum-riverbendsright": "jl-cibeureum-riverbendsright",
    "jl-cibeureum-riverbendsleft": "jl-cibeureum-riverbendsleft",
    "jl-cibeureum-lastbend": "jl-cibeureum-lastbend",
    "jl-cibeureum-harmony": "jl-cibeureum-harmony",
    "mulyaharja": "Mulyaharja",
    "ciampea-before-river": "ciampea-before-river",
    "ciampea-towards-iskandar": "ciampea-towards-iskandar",
    "kencana-1-bend-right": "kencana-1-bend-right",
    "kencana-2-bend-left": "kencana-2-bend-left",
    "kencana-3-over-river": "kencana-3-over-river",
    "kencana-4-setapak": "kencana-4-setapak",
    "kencana-5-left": "kencana-5-left",
    "kencana-6-right": "kencana-6-right",
    "kencana-corner-kalimurni": "kencana-corner-kalimurni",
    "kalimurni-1-right": "kalimurni-1-right",
    "kalimurni-2-left": "kalimurni-2-left",
    "kalimurni-pendidikan": "kalimurni-pendidikan",
    "taman griya kencana": "Taman Griya Kencana",
    "cimanggu-wates-1": "cimanggu-wates-1",
    "cimanggu-wates-setapak": "cimanggu-wates-setapak",
    "setapak-1": "setapak-1",
    "setapak-2": "setapak-2",
    "setapak-3": "setapak-3",
    "setapak-bukitcimanggu": "setapak-bukitcimanggu",
    "setapak-4": "setapak-4",
    "setapak-5": "setapak-5",
    "setapak-6": "setapak-6",
    "setapak-7": "setapak-7",
    "line-21-11": "line-21-11",
    "line-21-12": "line-21-12",
    "line-21-13": "line-21-13",
    "line-21-14": "line-21-14",
    "line-21-15": "line-21-15",
    "line-21-16": "line-21-16",
    "line-21-17": "line-21-17",
    "line-21-18": "line-21-18",
    "line-21-19": "line-21-19",
    "jl-bubulak-1": "jl-bubulak-1",
    "jl-bubulak-pondok-rumput": "jl-bubulak-pondok-rumput",
    "pondok rumput": "Pondok Rumput",
    "ciparigi-3": "ciparigi-3",
    "adnawijaya-1": "adnawijaya-1",
    "adnawijaya-2": "adnawijaya-2",
    "adnawijaya-3": "adnawijaya-3",
    "adnawijaya-4": "adnawijaya-4",
    "adnawijaya-5": "adnawijaya-5",
    "ciremai-1": "ciremai-1",
    "ciremai-2": "ciremai-2",
    "ciremai-3": "ciremai-3",
    "ciremai-4": "ciremai-4",
    "ciremai-5": "ciremai-5",
    "ciremai-6": "ciremai-6",
    "ciremai-7": "ciremai-7",
    "ciremai-8": "ciremai-8",
    "ciremai-9": "ciremai-9",
    "ciremai-jambudua": "ciremai-jambudua",
    "jambudua-1": "jambudua-1",
    "jambudua-2": "jambudua-2",
    "jambudua-3": "jambudua-3"
};

export function cariRute(asal, tujuan) {
    const normalAsal = normalisasiLokasi(asal);
    const normalTujuan = normalisasiLokasi(tujuan);

    const langsung = [];
    const transfer = [];

    // Cari rute langsung
    for (const trayek of trayekAngkot) {
        const idxAsal = temukan(trayek.rute, normalAsal);
        const idxTujuan = temukan(trayek.rute, normalTujuan);

        if (idxAsal !== -1 && idxTujuan !== -1 && idxAsal < idxTujuan) {
            langsung.push({
                trayek,
                dariStop: trayek.rute[idxAsal],
                keStop: trayek.rute[idxTujuan],
                stops: trayek.rute.slice(idxAsal, idxTujuan + 1)
            });
        }
    }

    // Cari rute transfer (ganti angkot 1x) jika tidak ada rute langsung
    if (langsung.length === 0) {
        for (const t1 of trayekAngkot) {
            const idxAsal1 = temukan(t1.rute, normalAsal);
            if (idxAsal1 === -1) continue;

            for (const stopTransfer of t1.rute.slice(idxAsal1 + 1)) {
                for (const t2 of trayekAngkot) {
                    if (t1.kode === t2.kode) continue;
                    const idxTransfer2 = temukan(t2.rute, stopTransfer);
                    const idxTujuan2 = temukan(t2.rute, normalTujuan);

                    if (idxTransfer2 !== -1 && idxTujuan2 !== -1 && idxTransfer2 < idxTujuan2) {
                        const idxAsal1Real = temukan(t1.rute, normalAsal);
                        const idxTransfer1 = temukan(t1.rute, stopTransfer);

                        const sudahAda = transfer.some(r =>
                            r.t1.kode === t1.kode && r.t2.kode === t2.kode && r.transfer === stopTransfer
                        );
                        if (!sudahAda && idxTransfer1 > idxAsal1Real) {
                            transfer.push({
                                t1,
                                t2,
                                transfer: stopTransfer,
                                stops1: t1.rute.slice(idxAsal1Real, idxTransfer1 + 1),
                                stops2: t2.rute.slice(idxTransfer2, idxTujuan2 + 1)
                            });
                        }
                    }
                }
            }
        }
    }

    return { langsung, transfer: transfer.slice(0, 3) };
}

function normalisasiLokasi(input) {
    const lower = input.toLowerCase().trim();
    return aliasLokasi[lower] || capitalizeWords(lower);
}

function temukan(rute, target) {
    const targetLower = target.toLowerCase();
    return rute.findIndex(stop => stop.toLowerCase().includes(targetLower) || targetLower.includes(stop.toLowerCase()));
}

function capitalizeWords(str) {
    return str.replace(/\b\w/g, c => c.toUpperCase());
}
